VisualCheck<-function(Vseq,Type,Signal){
  nExon<-length(Vseq)
  if(Signal==1){
    if(length(nchar(Type))<=3){
    NoSite1<-as.numeric(as.character(strsplit(Type,":")[[1]][1]))
    NoSite2<-as.numeric(as.character(strsplit(Type,":")[[1]][2]))
    }else{
    NoSite1<-as.numeric(as.character(strsplit(Type,":")[[1]][1]))
    NoSite2<-as.numeric(as.character(strsplit(Type,":")[[1]][2]))
    NoSite3<-as.numeric(as.character(strsplit(Type,":")[[1]][3]))
    NoSite4<-as.numeric(as.character(strsplit(Type,":")[[1]][4]))
    }
    
  

#first read
  if(NoSite1==NoSite2){
    if(Vseq[NoSite1]<(-1)){
      Vseq[NoSite1]<-Vseq[NoSite1]-10
    }
    if(Vseq[NoSite1]==-1){
      Vseq[NoSite1]<--10010
    }
    if(Vseq[NoSite1]==0){
      Vseq[NoSite1]<-1
    }
  }
 
  if(NoSite1==NoSite2-1){
    if(Vseq[NoSite1]<(-1)){
      Vseq[NoSite1]<-Vseq[NoSite1]-10
    }
    if(Vseq[NoSite1]==-1){
      Vseq[NoSite1]<--10010
    }
    if(Vseq[NoSite1]==0){
      Vseq[NoSite1]<-1
    }
    if(Vseq[NoSite2]<(-1)){
      Vseq[NoSite2]<-Vseq[NoSite2]-10
    }
    if(Vseq[NoSite2]==-1){
      Vseq[NoSite2]<--10010
    }
    if(Vseq[NoSite2]==0){
      Vseq[NoSite2]<-1
    }
  }

  if(NoSite1<NoSite2-1){
    if(Vseq[NoSite1]<(-1)){
      Vseq[NoSite1]<-Vseq[NoSite1]-10
    }
    if(Vseq[NoSite1]==-1){
      Vseq[NoSite1]<--10010
    }
    if(Vseq[NoSite1]==0){
      Vseq[NoSite1]<-1
    }
    if(Vseq[NoSite2]<(-1)){
      Vseq[NoSite2]<-Vseq[NoSite2]-10
    }
    if(Vseq[NoSite2]==-1){
      Vseq[NoSite2]<--10010
    }
    if(Vseq[NoSite2]==0){
      Vseq[NoSite2]<-1
    }
    for(j in (NoSite1+1):(NoSite2-1)){
      if(Vseq[j]<(-1)){
        Vseq[j]<-Vseq[j]-10000
      }
      if(Vseq[j]==0){
        Vseq[j]<--1
      }
      if(Vseq[j]==1){
        Vseq[j]<--10010
      }
    }
  }
  

if(length(nchar(Type))>3){
#second read  
  if(NoSite3==NoSite4){
    if(Vseq[NoSite3]<(-1)){
      Vseq[NoSite3]<-Vseq[NoSite3]-10
    }
    if(Vseq[NoSite3]==-1){
      Vseq[NoSite3]<--10010
    }
    if(Vseq[NoSite3]==0){
      if(NoSite3==1){print(c(Type,2))}
      Vseq[NoSite3]<-1
    }
  }
  
  if(NoSite3==NoSite4-1){
    if(Vseq[NoSite3]<(-1)){
      Vseq[NoSite3]<-Vseq[NoSite3]-10
    }
    if(Vseq[NoSite3]==-1){
      Vseq[NoSite3]<--10010
    }
    if(Vseq[NoSite3]==0){
      if(NoSite3==1){print(c(Type,2))}
      Vseq[NoSite3]<-1
    }
    if(Vseq[NoSite4]<(-1)){
      Vseq[NoSite4]<-Vseq[NoSite4]-10
    }
    if(Vseq[NoSite4]==-1){
      Vseq[NoSite4]<--10010
    }
    if(Vseq[NoSite4]==0){
      if(NoSite4==1){print(c(Type,2))}
      Vseq[NoSite4]<-1
    }
  }
  
  if(NoSite3<NoSite4-1){
    if(Vseq[NoSite3]<(-1)){
      Vseq[NoSite3]<-Vseq[NoSite3]-10
    }
    if(Vseq[NoSite3]==-1){
      Vseq[NoSite3]<--10010
    }
    if(Vseq[NoSite3]==0){
      if(NoSite3==1){print(c(Type,2))}
      Vseq[NoSite3]<-1
    }
    if(Vseq[NoSite4]<(-1)){
      Vseq[NoSite4]<-Vseq[NoSite4]-10
    }
    if(Vseq[NoSite4]==-1){
      Vseq[NoSite4]<--10010
    }
    if(Vseq[NoSite4]==0){
      if(NoSite4==1){print(c(Type,2))}
      Vseq[NoSite4]<-1
    }
    for(j in (NoSite3+1):(NoSite4-1)){
      if(Vseq[j]<(-1)){
        Vseq[j]<-Vseq[j]-10000
      }
      if(Vseq[j]==0){
        Vseq[j]<--1
      }
      if(Vseq[j]==1){
        Vseq[j]<--10010
      }
    }
  }

}
}
  return(t(t(Vseq)))
}